a= ("\\a Bell (alert)")
b= ("\\b Backspace")
c= ("\\n New line")
d= ("\\t Horizontal tab")
e= ("\\\ Backslash")
f= ("\\\" Double quotation mark")
g= ("\\' Single quotation mark")
print(a,"\n",b,"\n",c,"\n",d,"\n",f,"\n",g)
